Драфт представлений (MV) аггрегирующих данные от майнера и от внешнего API
nomium-org/stratum pull request #10
Opened 2024-12-19 20:34 UTC by mlgodskz

После запуска данные из представлений можно брать например так:

curl -X POST 'http://localhost:8123/' -H "X-ClickHouse-User: default" -H "X-ClickHouse-Key: 5555" -d "
SELECT 
    user_identity,
    worker_id,
    worker_name,
    sum(difficulty) as total_difficulty,
    count(*) as share_count
FROM mining.mv_shares_with_auth
WHERE timestamp >= now() - INTERVAL 1 HOUR
GROUP BY user_identity, worker_id, worker_name
FORMAT Pretty"

или 

curl -X POST 'http://localhost:8123/' -H "X-ClickHouse-User: default" -H "X-ClickHouse-Key: 5555" -d "
SELECT 
    user_identity,
    worker_id,
    worker_name,
    COUNT(*) as blocks_found,
    MIN(found_at) as first_block,
    MAX(found_at) as last_block
FROM mining.mv_blocks_with_auth
GROUP BY user_identity, worker_id, worker_name
FORMAT Pretty"

данные для доступа к БД поменять в запросе на свои

2024-12-19 23:48 UTC, AkulovOleg requested changes

2024-12-19 23:48 UTC, AkulovOleg commented on nomium/shares-logger/src/storage/clickhouse/service.rs
> +        self.client.query(CREATE_SHARES_WITH_AUTH_VIEW)
Я не очень понимаю для чего мы хотим использовать этот view?
Я был уверен, что мы просто заменим channel_id на worker_id в той таблице что мы сделали для шар, ну или просто добавим туда worker_id. 
Давай голосом обсудим как с этим планируется работа

2024-12-19 23:48 UTC, AkulovOleg commented on nomium/shares-logger/src/storage/clickhouse/service.rs
> +            .query(CREATE_BLOCKS_WITH_AUTH_VIEW)
Аналогично надо обсудить зачем этот view

2024-12-19 23:48 UTC, AkulovOleg commented on nomium/shares-logger/src/storage/clickhouse/queries/shares_table.sql
> +    user_identity String,
вот по мне сюда как раз правильно было бы поставить worker_id

2024-12-19 23:48 UTC, AkulovOleg commented on nomium/shares-logger/src/storage/clickhouse/queries/hashrate_view.sql
> +    user_identity,
И вот сюда worker_id потому что как раз все выборки будут по нему происходить

2024-12-19 23:48 UTC, AkulovOleg commented on nomium/shares-logger/src/services/authorization_processor.rs
> +use crate::models::AuthorizationLog;
Меня смущает что мы это положили в crate который называется shares-logger хотя оно никакое отношение к этому не имеет

2024-12-19 23:48 UTC, AkulovOleg commented on nomium/shares-logger/src/lib.rs
> +const API_BASE_URL: &str = "https://qa.redrockpool.com/equipment-api/v1";
Надо вынести в конфиг, для разных сред разные ссылки и ApiKey тоже

2024-12-20 09:16 UTC, mlgodskz commented on nomium/shares-logger/src/storage/clickhouse/service.rs
> +        self.client.query(CREATE_SHARES_WITH_AUTH_VIEW)
Это предварительная версия. Я как раз сейчас смотрел как это должно быть в идеале, и пришел к тому же выводу - это надо обсудить) Без полного понимания потребностей фронта в данных оптимальную структуру не сделать.

2024-12-20 09:19 UTC, mlgodskz commented on nomium/shares-logger/src/storage/clickhouse/service.rs
> +            .query(CREATE_BLOCKS_WITH_AUTH_VIEW)
Аааа... ты об этом, я не сразу понял) Я кладу данные от авторизационного API в отдельную таблицу, а потом аггрегирую их с blocks чтобы получилась сводная статистика. То же самое с сшарами во втором представлении.

2024-12-20 09:27 UTC, mlgodskz commented on nomium/shares-logger/src/storage/clickhouse/queries/shares_table.sql
> +    user_identity String,
Тут надо смотреть по производительности (это будет лишний подзапрос к таблице worker_auth) и всякому разному другому. 
Ну, например, авторизуется новый воркер, и какие-то там задержки с получением worker_id через API (внешнее API шутка такая), а от него уже начинают поступать шары, и что с ними делать если нет worker_id? А так мы просто кладем шары в БД и все. 
В общем, нужно проработать систему авторизации и ее взаимодействие с основным потоком шар, согласен. 
Может ты и прав.

2024-12-20 09:29 UTC, mlgodskz commented on nomium/shares-logger/src/storage/clickhouse/queries/hashrate_view.sql
> +    user_identity,
т.е. worker_id это у нас первичный ключ для запросов с фронта? окок, принято.

2024-12-20 09:33 UTC, mlgodskz commented on nomium/shares-logger/src/services/authorization_processor.rs
> +use crate::models::AuthorizationLog;
Ну, по сути ты прав насчет названия. Мб стоит просто переименовать крейт.... Ок, давай подумаем тоже. Отдельный крейт создавать под этот функционал я смысла не вижу, это скорее усложнит структуру чем упростит.

2024-12-20 11:24 UTC, AkulovOleg commented on nomium/shares-logger/src/services/authorization_processor.rs
> +use crate::models::AuthorizationLog;
Да, можно переименовать

2024-12-22 13:23 UTC, closed without merging