169-11 worker_id пробрасывается из Translator в shares-logger и логгируется в Кликхаус
nomium-org/stratum pull request #11
Opened 2024-12-21 20:23 UTC by mlgodskz

справка по работе с MV: https://github.com/nomium-org/stratum/blob/169-11-New-worker_id/nomium/shares-logger/README-RU.md

2024-12-22 17:51 UTC, AkulovOleg requested changes

2024-12-22 17:51 UTC, AkulovOleg commented on nomium/shares-logger/src/models/share_log.rs
> +            ("user_identity".to_string(), self.user_identity.clone()),
В итоге так и не понял почему тут только user_identity, а нету worker_id

2024-12-22 17:51 UTC, AkulovOleg commented on nomium/shares-logger/src/services/share_processor.rs
> +            .unwrap_or("unknown")
Есть ощущение, что это костыль, не?

2024-12-25 10:13 UTC, AkulovOleg requested changes

2024-12-25 10:13 UTC, AkulovOleg commented on roles/translator/src/lib/downstream_sv1/downstream.rs
> +                let api_url = env::var("REDROCK_API_URL")
Не хотим вынести куда-то в метод приватный хотя бы?

2024-12-25 10:13 UTC, AkulovOleg commented on roles/.env
> +REDROCK_API_KEY=ZcU8z5W87ufe
Давай в репу закинем пустое значение тут в ApiKey

2024-12-25 10:13 UTC, AkulovOleg commented on nomium/shares-logger/src/storage/clickhouse/queries/hashrate_view.sql
> +    sum(CASE WHEN share_status = 0 THEN 1 ELSE 0 END) AS refused_shards,
Можешь объяснить логику вот этого расчёта refused_shards тут сейчас может быть только 1 и 0 не оч понимаю как потом с этим работать

2024-12-25 19:50 UTC, mlgodskz commented on roles/translator/config-examples/tproxy-config-local-pool-PoolTest.toml
> +min_individual_miner_hashrate=5_000_000.0
Хороший вопрос, я его сам хотел поднять сейчас)) я это вообще исключу из гита, потому что конфиг должен быть для каждого пула (моего и тестировочного) свой. Дело в том, что Vardiff транслятора как раз и стартует на значении зависящим от min_individual_miner_hashrate и других параметров в этом конфиге, иными словами для асика нужно писать 130_000_000_000_000.0 тогда он сарзу стартанет на нужной сложности +-

2024-12-25 19:54 UTC, mlgodskz commented on roles/translator/src/lib/downstream_sv1/downstream.rs
> +                    .timeout(std::time::Duration::from_secs(5))
Это произвольное значение. Главное чтобы токио-канал не подвисал навечно, если API ляжет

2024-12-25 19:56 UTC, mlgodskz commented on nomium/shares-logger/src/services/share_processor.rs
> +            .unwrap_or("unknown")
скорее to_do ) мы же говорили, что обработку ошибок нужно делать отдельным фронтом работ

2024-12-25 20:01 UTC, mlgodskz commented on roles/translator/config-examples/tproxy-config-local-pool-PoolTest.toml
> +shares_per_minute = 20.0
ну ты же не думаешь что я под гипнозом это делал)) количество шар в минуту я менял чтобы посмотреть на зависимость влияния этого прараметра на сложность target - в общем, все это менялось по ходу исследования. вообще, см. выше - конфиг на то и конфиг, что мы его будем менять постоянно, подстраивать под наши потребности, в общем, я его выкину из git, поскольку менять состав переменных мы все равно не будем, а на сервере и у меня локально они все равно будут разные. наш .env пока в гите оставлю - мы туда возможно еще переменных добавим, хотя бы и тот же самый timeout о котором была речь выше (я о нем просто забыл, когда env делал).

2024-12-25 20:21 UTC, mlgodskz commented on roles/translator/src/lib/downstream_sv1/downstream.rs
> +                    .timeout(std::time::Duration::from_secs(5))
вынес в .env

2024-12-25 20:25 UTC, mlgodskz commented on nomium/shares-logger/src/storage/clickhouse/queries/hashrate_view.sql
> +    sum(CASE WHEN share_status = 0 THEN 1 ELSE 0 END) AS refused_shards,
эта строка авторства Андрея - я просто принял ее пока что как есть и не вникал) но готов завтра с ним обсудить )) вообще, там есть определенное количество todo до которых пока не доходили руки - нужно было в первую очередь написать основной пайплайн - видимо теперь пришло их время, как в случае и с хэшрейтом - раньше я просто забивал на то, что он в два раза больше был - типа считает как-то ну и ладно, потом разберемся когда основу сделаем, вот видишь дошла до него очередь и вроде разобрались по ходу, так и с остальными вопросами

2024-12-25 20:26 UTC, mlgodskz commented on nomium/shares-logger/src/storage/clickhouse/queries/hashrate_view.sql
> +    sum(CASE WHEN share_status = 0 THEN 1 ELSE 0 END) AS refused_shards,
"эта строка авторства Андрея" - ...но возможно и моего, просто месяц-два назад)) я мог и забыть ) однако это не суть, завтра решим что с этим делать

2024-12-26 09:47 UTC, AkulovOleg commented on nomium/shares-logger/src/storage/clickhouse/queries/hashrate_view.sql
> +    sum(CASE WHEN share_status = 0 THEN 1 ELSE 0 END) AS refused_shards,
Обсудите плиз что с ней делать

2024-12-26 09:55 UTC, AkulovOleg approved these changes

2024-12-26 09:56 UTC, merged