Shares Logger (see README.md)
nomium-org/stratum pull request #5
Opened 2024-11-18 10:21 UTC by mlgodskz

Shares Logger (see README.md)

2024-11-18 18:36 UTC, AkulovOleg requested changes

2024-11-18 18:36 UTC, AkulovOleg commented on nomium/shares-logger/src/services/clickhouse.rs
> +        Self {
Давай пустую строку перед, чтобы читаемость повысить

2024-11-18 18:36 UTC, AkulovOleg commented on nomium/shares-logger/src/services/clickhouse.rs
> +        let should_flush = self.batch.len() >= SETTINGS.clickhouse.batch_size ||
Т.е. мы тут кидаем батчами только? Типа если 1 шара будет то мы её не запишем вообще?

2024-11-18 18:36 UTC, AkulovOleg commented on nomium/shares-logger/src/services/clickhouse.rs
> +        self.ensure_table_exists().await?;
Думаешь есть смысл каждую запись это делать? Давай сделаем при запуске просто, вот создали объект ClickhouseService и проверили таблицу сразу

2024-11-18 18:36 UTC, AkulovOleg commented on nomium/shares-logger/src/services/clickhouse.rs
> +            info!("Prepared record {}/{}: hash={}, extranonce={}",
Вот эти логи сейчас в консоль пишутся, а можно ли в данном решении поменять их на file?

2024-11-18 18:36 UTC, AkulovOleg commented on nomium/shares-logger/src/services/clickhouse.rs
> +        let mut insert = self.client.insert("shares")?;
давай назовём переменную чуть более понятно

2024-11-19 08:51 UTC, mlgodskz commented on roles/Cargo.lock
> +name = "android-tzdata"
В общем, суть в том, что - да, оно у них организовано через воркспейс, и карго все стаскивает в единый лок-файл. Все что мы видим здесь - это нормально) И то что он ставит номера версий там где их раньше не было - тоже нормально. Другое дело, что да, к зависимостям придется подходить более ответственно. Мы потом, как будет у нас близко к финальной версии - покажем ребятам из SRI - послушаем что они скажут.

2024-11-19 09:09 UTC, mlgodskz commented on nomium/shares-logger/Cargo.toml
> +edition = "2021"
Олег, насколько я понимаю, 2024 то ли еще не существует, то ли совсем сырая, другие крейты (роли) тоже используют 2021 и даже 2018. Так что 2021 - оптимальный вариант.

2024-11-19 09:11 UTC, mlgodskz commented on nomium/shares-logger/src/config/default_config.toml
> +url = "http://localhost:8123"
Это уже голосом вчера обсуждали - это дефолтовые настройки и по сути это хардкод, но мы всегда можем их перезаписать через переменные окружения без пересборки крейта.

2024-11-19 09:21 UTC, mlgodskz commented on nomium/shares-logger/src/services/clickhouse.rs
> +        let should_flush = self.batch.len() >= SETTINGS.clickhouse.batch_size ||
У нас тут двояко: 
batch_size = 2
batch_flush_interval_secs = 5
это из конфига, оно пишет И по наполнении батча, И в любом случае через интервалы времени. 
вообще, запись в БД - это отдельная песня, мы сделаем пул соединений с БД потом, и все у нас будет просто прекрасно)

2024-11-19 09:29 UTC, mlgodskz commented on nomium/shares-logger/src/services/clickhouse.rs
> +            info!("Prepared record {}/{}: hash={}, extranonce={}",
да, можем, но тогда нам придется либо хардкодить абсолютный путь, либо делать директорию относительно Pool - ибо у нас пути от нее считаются. 
вообще, если по-хорошему, надо писать в "условный редис" )))))))) только морду к нему какую-то найти готовую, в общем, я рассмотрю вопрос, сделаю по-нормальному.

2024-11-19 09:44 UTC, mlgodskz commented
/refresh

2024-11-19 09:47 UTC, mlgodskz commented on nomium/shares-logger/src/config/settings.rs
> +        let settings = builder.try_deserialize::<Settings>();
ага, тут я пропустил несколько мессаджей - гитхаб их под кат поместил зачем-то) сейчас доделаю

2024-11-19 09:54 UTC, mlgodskz commented on nomium/shares-logger/src/models/clickhouse_share.rs
> +    pub is_valid: u8,
тут несколько больше работы, сначала мелкие правки внесу, потом эту, потом как доделаю все - еще один ре-реквест сделаю. пока ниже можешь не смотреть.

2024-11-19 10:02 UTC, mlgodskz commented on nomium/shares-logger/src/models/clickhouse_share.rs
> +    pub sequence_number: u32,
я вчера после нашего разговора пока котов кормил вспомнил)) это uid для куска работы порученного конкретному майнеру. 

о! Олег, я вчера несколько косноязчно изложил вопрос, потому и не получил внятный ответ) а мы можем списком изложить ИСЧЕРПЫВАЮЩИЕ требования к нашему логгеру с точки зрения конечного пользователя? 

смысл в том, что на основании этого списка мы уже сформируем итоговый список полей для таблицы. 

просто я хочу избежать ситуаций, когда мы повыкидываем все "ненужное", а оно потом окажется нужное)) тоже в принципе ничего страшного конечно - если надо добавим снова, но все таки хорошо бы такой список иметь перед глазами.

2024-11-19 10:02 UTC, AkulovOleg commented on nomium/shares-logger/src/models/clickhouse_share.rs
> +    pub is_valid: u8,
Не надо ещё 1 реквест, давай в этой ветке всё доделаем и зальём уже

2024-11-19 10:03 UTC, AkulovOleg commented on nomium/shares-logger/src/services/clickhouse.rs
> +            info!("Prepared record {}/{}: hash={}, extranonce={}",
Я ещё пока думаю, что будем использовать для логов, возможно grafana loki

2024-11-19 10:26 UTC, mlgodskz commented on nomium/shares-logger/src/services/difficulty.rs
> +        let shift_amount = numerator.bits().max(denominator.bits()).saturating_sub(53);
Это такой хитрый трюк, связанный с тем, что нам приходится делить два огромных числа одно на другое, и делаем это мы в формате f64, то есть мы ужимаем их до размера не более чем 52+1 бит - это количество бит в котором хранится f64, иначе у нас будет переполнение буфера) То есть мы как бы сначала сокращаем макс_таргет и таргет на какое-то количество порядков, чтобы они влезли в f64 и затем делим. 
На самом деле тут есть всякие варианты, но этот быстрый и работает )

2024-11-20 14:05 UTC, AkulovOleg commented on roles/Cargo.lock
> +name = "android-tzdata"
Так а ты разобрался что за зависимости поставились? Мне не нравится слово android

2024-11-20 14:06 UTC, AkulovOleg commented on nomium/shares-logger/src/services/clickhouse.rs
> +        self.ensure_table_exists().await?;
Пул соединений нужен чтобы большой объём данных асинхронно закидывать и разбирать все что копится по батчам?

2024-11-20 14:06 UTC, AkulovOleg commented on nomium/shares-logger/src/services/clickhouse.rs
> +            info!("Prepared record {}/{}: hash={}, extranonce={}",
пока пусть в stdout пишет

2024-11-22 10:37 UTC, mlgodskz commented on nomium/shares-logger/src/services/clickhouse.rs
> +        self.ensure_table_exists().await?;
Ну типа того. Смысл в том, чтобы держать открытыми какое-то количество соединений, чтобы они всегда были "под рукой") потому что на открытие тратится относительно много времени

2024-11-23 10:13 UTC, AkulovOleg commented on nomium/shares-logger/src/services/clickhouse.rs
> +        self.ensure_table_exists().await?;
понял, пул потоков короче)

2024-11-26 22:51 UTC, AkulovOleg approved these changes

2024-11-26 22:52 UTC, merged