RRP-211:  Log blocks to clickhouse
nomium-org/stratum pull request #7
Opened 2024-11-27 18:51 UTC by mlgodskz

Оно работает, но еще нужны доработки

Детали в ридми

2024-11-29 08:15 UTC, bymagka commented on nomium/shares-logger/tests/share_types_test.rs
> +        Ok(())
какой то странный init
что он делает? или это заготовка

2024-11-29 08:18 UTC, bymagka commented on nomium/shares-logger/tests/share_types_test.rs
> +        Ok(())
а , это реализация просто

2024-12-01 11:43 UTC, AkulovOleg requested changes

2024-12-01 11:43 UTC, AkulovOleg commented on nomium/shares-logger/src/models/block_found.rs
> +        self.block_hash.len() == 32
32 это чтобы сложности соответствовало? Просто не оч понял почему в Share мы validate не делаем, а тут делаем

2024-12-03 16:36 UTC, mlgodskz commented on nomium/shares-logger/Cargo.toml
> +log = "^0.4"
Олег, это дискуссионный вопрос) Соль в том, что когда с шапочками - оно старается подстроиться под уже существующие версии, то есть по идее в карго.лок меньше правок.

2024-12-03 16:57 UTC, mlgodskz commented on nomium/shares-logger/src/storage/clickhouse/queries/blocks_table.sql
> +    timestamp UInt64,
timestamp - это то что нам в шаре приходит от воркера, а found_at это время сервера на момент записи. возможно стоит переименовать для понятности?

2024-12-03 17:01 UTC, mlgodskz commented on nomium/shares-logger/src/models/block_found.rs
> +        self.block_hash.len() == 32
это на данном этапе заготовка. я в дальнейшем когда буду править этот функционал - добавлю //  TODO как в основном коде -- давай я этим займусь как у нас весь пайплайн будет поднять на сервере и user_identity будет тоже реализован?

2024-12-03 17:06 UTC, mlgodskz commented on nomium/shares-logger/src/models/block_found.rs
> +        self.block_hash.len() == 32
> 32 это чтобы сложности соответствовало?

Это не сложность, просто длина. Ну по сути просто то же самое true возвращаем.

У нас теперь трейты (интерфейсы в других языках) и нам async fn validate непременно надо реализовать в любом виде.

2024-12-03 18:12 UTC, AkulovOleg commented on nomium/shares-logger/src/storage/clickhouse/queries/blocks_table.sql
> +    timestamp UInt64,
да, давай переименуем worker_time и found_at можно в целом

2024-12-03 18:13 UTC, AkulovOleg commented on nomium/shares-logger/Cargo.toml
> +log = "^0.4"
Подозреваю, что это работает как с npm пакетами, он берёт latest версию из того что есть, но это может привести к невидимому обновлению минорной версии, а некоторые хреновые разработчики могут допустить регресс и там. Поэтому давай плиз зафиксируем конкретные

2024-12-03 20:32 UTC, mlgodskz commented on nomium/shares-logger/src/storage/clickhouse/queries/blocks_table.sql
> +    timestamp UInt64,
переименовал в ntime (это исходное имя поля в шаре), заодно один косяк поправил)

2024-12-03 20:32 UTC, mlgodskz commented on nomium/shares-logger/Cargo.toml
> +log = "^0.4"
окок, убрал)

2024-12-08 16:49 UTC, AkulovOleg approved these changes

2024-12-08 16:49 UTC, merged